Style/RescueModifier:
  Exclude:
  - 'lib/occi/core/parsers/json/entity.rb'
  - 'lib/occi/core/parsers/text/entity.rb'

Lint/RescueWithoutErrorClass:
  Exclude:
  - 'lib/occi/core/parsers/json/entity.rb'
  - 'lib/occi/core/parsers/text/entity.rb'
